import java.util.ArrayList;

public class Airport
{
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights)
    {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights()
    {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue()
    {
        /* to be implemented in part (a) */
        double revenue = 0;
        for (Flight flight : allFlights)
        {
            if (flight.getNumPassengers() > flight.getCapacity())
            {
                revenue = revenue + (flight.getPrice() * flight.getCapacity());
            }
            else
            {
                revenue = revenue + (flight.getPrice() * flight.getNumPassengers());
            }
        }
        return revenue;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights()
    {
        /* to be implemented in part (b) */
        int flightSize = 0;
        int minimum = 0;
        int passengers = 0;

        for (int i = allFlights.size() - 1; i >= 0; i--)
        {
            Flight temp = allFlights.get(i);

        }
    }
}
